### ISSUE TITLE
[6.2.6] 다른 언어에서의 구조체 예시

### ISSUE THREAD

**Issue by minjeekang** [AskMePlz/standardOfJava#1]
구조체 : 서로 관련된 여러 데이터를 종류에 관계없이 하나의 집합으로 저장할 수 있는 공간
자바에서는 구조체가 없는데 혹시 다른 언어에서 구조체의 예를 알고 싶어요!

**Comment by leechGamer** [comment]
자바에서 struct 예약어도 없고 구조체를 사용하지 않아서 
c언어 구조체를 예로 들게요

```
typedef struct_tv{
String color;
boolean color;
int channel;
}TV
```
클래스는 구조체에다가 함수를 더한거라고 생각하시면 될 것 같아요. (p.243 참고)
