### ISSUE TITLE
[7.5.1] 다형성의 활용 예시

### ISSUE THREAD

**Issue by minjeekang** [AskMePlz/standardOfJava#10]
다형성 관련하여 실제 프로그램에서 사용할 수 밖에 없는 예시 등이 있을까요?
이론은 여러번 읽으니 이해가 가는데 좀더 와닿는 예시가 있으면 기억이 오래갈 것 같아 질문 남겨요!

(예: 사전예약 프로그램을 만들었는데 이러이러한 경우 필요하다 --> 이런 일상적인 예시를 알고 싶어요!)

**Comment by peacebestill0314** [comment]
오버로딩이나 오버라이딩, 람다식의 함수형 인터페이스가 모두 다형성을 활용한 것이에요!
