### ISSUE TITLE
[7.6.2] 모든 추상 메서드를 구현하지 않는다면 자식 또한 추상클래스여야 하는 이유

### ISSUE THREAD

**Issue by peacebestill0314** [AskMePlz/standardOfJava#11]
[조상으로부터 상속받은 추상메서드 중 하나라도 구현하지 않는다면 자손 클래스 역시 추상 클래스로 지정해 주어야 한다. (p376)]
[구현하는 인터페이스의 메서드중 일부만 구현한다면, abstract를 붙여서 추상클래스로 선언해야 한다.  (p383)]
추상메서드나 인터페이스 둘다 강제하는 모든 메서드를 구현하지 않는다면 하위 클래스도 추상클래스로 만들어야 하는데
추상 클래스의 어떤 특성 때문에 그런건가요?!?!

**Comment by HyunJungLee2** [comment]
추상클래스를 상속받은 자손클래스는 프로그램의 안전성 향상을 위하여 부모의 추상메서드를 반드시 구현하도록 강제성이 내포되어있습니다.
