### ISSUE TITLE
[6.3.5] static 메서드와 인스턴스 메서드 호출 관련

### ISSUE THREAD

**Issue by minjeekang** [AskMePlz/standardOfJava#2]
P255 하단 "메서드의 실행흐름" 바로 밑 단락입니다.

static 메서드는 같은 클래스 내의 인스턴스 메서드를 호출할 수 없다.

해당 부분의 보다 자세한 내용(이유 등)을 알고 싶습니다.

**Comment by leechGamer** [comment]
인스턴스 메소드(non-static method)는 인스턴스가 존재해야만 call 할 수 있는데요, 
인스턴스 생성없이 call하는 것을 방지하기 위해서 자체적으로 막는 겁니다.

반면 Static메서드는 class 자체에 포함되어 있어서 언제나 존재하기에 인스턴스 메소드(non-static method)에서 사용하는 것이 가능합니다.

저희 다음 스터디 범위인 (p.278을 참고해주세요)
