### ISSUE TITLE
[6.3.11]  클래스 멤버 메모리 

### ISSUE THREAD

**Issue by peacebestill0314** [AskMePlz/standardOfJava#4]
클래스 멤버가 올라가는 static 메모리 영역도 GC 대상이 될 수 있나여?!?!

**Comment by minjeekang** [comment]
Garbage Collector는 "Heap" 에서  참조되지 않는 메모리를 확인하고 제거하며 Static 영역은 GC의 대상은 아닙니다.

<h3>추가 참고 사항</h3>
* Static영역에 생성(할당)될 경우 JVM이 종료될 때까지 사라지지않고 고정된 상태로 유지됩니다.
<br><br>
JVM 메모리 구조 (주요영역)

|Static(Method Area/Class Area)|Call Stack|Heap|
|---|---|---|
|클래스, 인터페이스, 메소드, 필드 static 변수 등|메서드 호출 시, 각각 스택 프레임 생성(매개변수, 지역변수, 리턴 값 등 ), 수행 종료 시 프레임 별 삭제|인스턴스 생성 공간(new 키워드로 생성되는 객체, 배열)|

**Comment by gyoungeunbae** [comment]
클래스 변수가 static 메모리 영역에 계속 올라가 있기 때문에 (gc의 관리 대상이 아니고, static 영역에 계속 떠 있기 때문에)
클래스 변수 사용시 추적이 어려워서 클래스 변수를 사용하지 않는 것도 있지만
메모리 관리 측면에서 class변수를 잘 사용하지 않는 이유도 있습니다.
