### ISSUE TITLE
[6.6.4] 멤버변수의 초기화 시기와 순서

### ISSUE THREAD

**Issue by leechGamer** [AskMePlz/standardOfJava#5]
p. 305
> 클래스의 로딩시기는 JVM의 종류에 따라 좀 다를 수 있는데, 클래스가 필요할 때 바로 메모리에 로딩하도록 설계가 되어있는 것도 있고, 실행효율을 높이기 위해서 사용될 클래스들을 프로그램이 시작될 때 미리 로딩하도록 되어있는 것도 있다.

JVM 종류에 따른 클래스의 로딩 시기가 궁금합니다.

**Comment by minjeekang** [comment]
해당 이슈는 조사가 어려워 자바카페에 질문 등록 진행 예정입니다 혹시 다른 분들이 찾으셨으면 같이 답변 남겨주셔도 좋을 것 같습니다 : )

**Comment by minjeekang** [comment]
![스크린샷 2021-12-14 오후 3 02 36](https://user-images.githubusercontent.com/60434240/145943461-58f28372-3be6-47a4-ba3a-84eabf1e3e55.png)

저자 답변입니다! 이 정도로 이해하고 진행하면 될 것 같습니다 : )
