### ISSUE TITLE
[6.6.1] 변수의 초기화

### ISSUE THREAD

**Issue by HyunJungLee2** [AskMePlz/standardOfJava#6]
멤버변수는 초기화를 하지 않아도 자동으로 변수의 자료형에 맞는 기본값으로 초기화가 이루어지고 지역변수는 사용하기전 반드시 초기화가 필요하다 하는데 그 이유가 궁금합니다.

**Comment by minjeekang** [comment]
지역변수는 대부분 메서드 내에서 계산을 수행하기 위해 선언됩니다.  따라서 초기화 되어 있지 않으면 예기치 않은 값이  출력될 수 있습니다. 따라서 컴파일러는 정의되지 않은 값의 사용을 피하기 위해 변수에 액세스 하기 전에 초기화 하도록 요청(에러발생)하는 것입니다.


참고로 이와 같은 이슈로 토론한 페이지가 있는데 "결과를 위해 내부적으로 돌아가는 것이고 이 것이 자바의 스펙이다"라는 의견이 있습니다 -> 개인적으로 가장 인상깊은 의견이네요 : ) 

동일 이슈로 토론한 내용 링크 첨부하니 시간될 떄 참고하면 좋을 것 같습니다.
[`[지역변수 초기화에 따른 토론 바로가기]`](https://slipp.net/questions/162)
