### ISSUE TITLE
[7.1.5] 자식 클래스의 실행파일

### ISSUE THREAD

**Issue by leechGamer** [AskMePlz/standardOfJava#8]
p.332 페이지를 보시면
> object클래스를 제외한 모든 클래스의 생성자 첫줄에 super()를 호출하지 않으면, 컴파일러가 자동으로 super()를 생성자의 첫줄에 삽입한다.

만약 p.332 페이지의 말이 맞다면, 
실행파일을 까보면 super()라는 문장이 들어있을텐데, 진짠지 알려주세요..
(모든 class 들은 Object를 상속받으니 그것도 들어있는지 좀.. )

**Comment by leechGamer** [comment]
실행파일 까면 컴파일러가 알아서 추가하는 것들 
그냥 알고가는 거랑 실제로 보는거랑 다를 것 같아서 질문 남겨요

**Comment by peacebestill0314** [comment]
디컴파일 내역에 안나와서 찾아보니 아래와같다고 하네요! 
https://stackoverflow.com/questions/24722480/cant-see-super-in-class-file-after-decompiling
